name: frontend
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^1.1.0 
  email_validator: ^2.1.17
  flutter_spinkit: ^5.2.0
  loading_animation_widget:
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.0.9
  intl: ^0.18.0
  date_time_picker_widget: ^2.0.0
  dotted_line: ^3.2.2
  test: ^1.24.9
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path : ^1.9.0
  flutter_local_notifications: ^17.1.1
  timezone: ^0.9.3
  permission_handler: ^11.3.1
  flutter_app_badger: ^1.5.0
  flutter_native_timezone: ^2.0.0
  signature : ^5.4.1
  firebase_messaging: ^14.9.2
  firebase_core: ^2.31.0


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/