name: frontend
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^1.1.0 
  email_validator: ^2.1.17
  flutter_spinkit: ^5.2.0
  loading_animation_widget:
  flutter_svg: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/